# Generated by Django 2.1.5 on 2019-01-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190123_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tempurature',
            new_name='Temperature',
        ),
    ]
