# Generated by Django 2.1.5 on 2019-04-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190123_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('recorded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='humidity',
            name='change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='humidity',
            name='recorded_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='humidity',
            name='rh',
            field=models.FloatField(default=0.0),
        ),
    ]
